import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import ReadyToGetStarted from "@/components/layout/ReadyToGetStarted";
import Provider from "@/context/Provider";
import "./globals.css";
import AppModal from "@/components/layout/AppModal";

export const metadata = {
  title: "Sodality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
          <ReadyToGetStarted />
          <Footer />
          <AppModal/>
        </Provider>
      </body>
    </html>
  );
}
